ICE-STUDYRES/ice-studyroom

backend/src/main/java/com/ice/studyroom/IceStudyRoomApplication.java
backend/src/main/java/com/ice/studyroom/domain/reservation/api/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ScheduleRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/global/dto/response/ResponseDto.java
backend/src/main/java/com/ice/studyroom/global/exception/BusinessException.java
backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/ice/studyroom/global/type/StatusCode.java

- 공통 응답 처리를 통한 프론트엔드 데이터 통일성 향상
- 예약, 스케줄 조회 API 구현
- #18
- #19 
테스트 코드 학습하고 있으니, 다음 PR에 추가할 예정입니다.

[BE -#18, #19]공통 응답 및 예약, 스케줄 조회 API 구현

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
backend/src/main/java/com/ice/studyroom/domain/identity/exception/InvalidRefreshTokenException.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java

레디스로 Refresh 토큰을 관리합니다.
기존에는 Refresh 토큰 자체에 만료기한을 설정해서 전달해줬으나, Redis의 TTL 기능을 사용해서 만료 기한을 관리합니다.
Refresh 토큰을 사용함으로써, 재로그인을 하지않고도 로그인 유지가 가능해집니다.
- #46 

[BE -#46] 토큰 재발급 구현

---

backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberCreateResponse.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberResponse.java

로그아웃을 할 경우 레디스에서 관리하던 Refresh Token을 삭제합니다.
이는 해커가 탈취한 Access Token과 Refresh Token으로 재로그인을 할 수 없게 합니다.
- #47 

[BE -#47] 로그아웃 구현

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Penalty.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyReasonType.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyStatus.java
backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/PenaltyRepository.java
backend/src/main/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateScheduler.java
backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java

- 패널티 비즈니스 로직 중 하나인 유효 횟수를 시행하지 않기로 하여, 이에 따른 member, penalty의 DDL을 수정하였습니다.
- penalty 업데이트 스케줄러 코드도 업데이트하였습니다.
#106 
`penalty_end` 를 오름차순으로 인덱스 설정한 이유에 대한 글을 정리했습니다.
https://www.notion.so/penalty_end-f4c47ecffca4429580ae72003058604a

[BE - #106] member, penalty table 변경에 따른 코드 수정

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/EncryptionService.java
backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/QRCodeService.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/AESUtil.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/QRCodeUtil.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/QrController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/QrEntranceRequest.java
backend/src/main/java/com/ice/studyroom/global/exception/AttendanceException.java
backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrRecognitionServiceTest.java
backend/src/test/java/com/ice/studyroom/helper/ReservationTestHelper.java

- 이제 프론트엔드에서 전달된 QR Code 이미지를 서버에서 처리하여 입실을 처리할 수 있습니다.
- 출석 이전: 스터디룸 시작 시간 이전에 QR Code 사용 시 403 반환
- 출석: 스터디룸 시작 시간부터 30분 이내 QR Code 사용 시 200과 ENTRANCE 반환
- 지각: 스터디룸 시작 시간부터 30분 초과 스터디룸 종료 시간 이내 QR Code 사용 시 200과 LATE 반환
- 만료: 스터디룸 시작 시간부터 종료 시간 초과 QR Code 사용 시 401 반환
- 프론트엔드에서 전송된 PNG를 BASE64로 디코딩 후 텍스트를 추출하는 과정에서 오류 발생
- PNG를 BASE64로 변환하지않았던 오류 수정
- 레디스에 저장된 QR 데이터를 반환하는 과정에서 reservation의 고유 ID를 Long으로 변환하지 못하는 오류 수정
- #31 

[BE-#31] QR 입실 구현

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
backend/src/main/java/com/ice/studyroom/domain/identity/domain/application/EmailVerificationService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/type/PenaltyStatus.java
backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyReasonType.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyStatus.java
backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/global/dto/request/EmailRequest.java
backend/src/main/java/com/ice/studyroom/global/service/EmailService.java
backend/src/main/java/com/ice/studyroom/global/service/GmailService.java
backend/src/test/java/com/ice/studyroom/domain/membership/infrastructure/email/EmailVerificationServiceTest.java
backend/src/test/java/com/ice/studyroom/domain/membership/scheduler/PenaltyUpdateSchedulerTest.java
backend/src/test/java/com/ice/studyroom/domain/penalty/application/PenaltyServiceTest.java

- 이메일 발송 로직 추상화
- 패널티 계층 분리
- 패널티 유형 시간 정리
- 노쇼 패널티 스케줄러 제작
#127 #128 #129 
현재 Penalty는 `membership`(회원), `reservation`(예약), `admin`(관리자) 도메인들과 밀접하게 연관됩니다.
Penalty 계층을 membership 내에 생성해두었는데, 여러 도메인에서 사용되는 것을 감안하여 독립적인 도메인으로 봐야한다고 판단하여 이를 분리하는 작업을 진행했습니다.
```java
@Getter
@RequiredArgsConstructor
public enum PenaltyReasonType {
CANCEL(2),
LATE(3),
NO_SHOW(7);
private final int durationDays;
}
```
취소(1시간 전) | 2일
-- | --
지각 | 3일
노쇼 | 7일
예 ) `1.1 13:30`에 지각 패널티가 부여될 경우 
- `1.4 23:59` 까지는 패널티 상태,
- `1.5 00:00` 에 스케줄러를 통해 패널티 해제
주말 여부는 따로 반영하지 않았습니다.
```java
@Scheduled(cron = "0 1 10-23,0 * * *") // 매일 10:01 ~ 23:01, 자정 00:01 실행
public void checkNoShowPenalty() {
LocalTime now = LocalTime.now().withSecond(0).withNano(0);
List<Reservation> expiredReservations = …
```

[BE-#127 #128 #129] Penalty 도메인 분류 및 노쇼 확인 스케줄러 생성

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/CancelReservationResponse.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrRecognitionServiceTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java

- 예약 취소를 가능하게 합니다.
- 취소할 경우 다음과 같은 로직이 구현됩니다.
- 현재 예약 인원에서 1을 차감합니다. 
- 현재 예약 인원이 0이면 status를 AVALIABLE로 변경합니다.
- 위의 로직은 예약에 해당하는 모든 스케줄에 반영됩니다.
- 입실까지 1시간 이하인 시간에 취소할 경우 패널티 부여 로직 구현
- #134 
테스트 코드와 출력부분은 삭제할 예정

[BE-#134] 예약 취소 기능 구현

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java

1. 현재 시각 이전 스케줄에 대해서 예약 불가 기능 추가
-> validateSchedulesAvailable 메서드 수정
(#136)
현재시각 이후의 스케줄에 대해서는 예약이 가능하지만
이전스케줄에 대해서는 예외처리 완료 
-> 현재 모든 예외처리에 대한 이유반환은 되어있지 않습니다.
또한 개인예약/단체예약 전용방에 대한 예약설정을 해놓아 개인예약 테스트시 방예약 상태를 바꿔줘야 합니다.
@glaxyt 님이 스케줄 검사에 대한 메서드를 따로 분리해주셔서 수정이 쉬웠습니다.

[BE-#136] 현재 시각 이전 스케줄에 대해서는 예약 불가 추가

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetReservationsResponse.java

- 내 예약 조회 api 응답에 참여자 정보를 추가했습니다.
#151 
기존 응답에서 예약별로 참여자 배열인  participants 배열을 추가했습니다.

[BE-#151] 내 예약 조회 api 참여자 정보 반영

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/JwtToken.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberLoginRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java

- 로그인 시 사용자 권한을 반환하기에 권한에 따른 라우팅이 가능합니다.
- Security Config에 일반 사용자나 비회원이 관리자 API에 접근할 수 없게 구현했습니다.
- 다만 현재 주석 처리를 했으니 프론트엔드가 구현을 마무리하면 활성화 할 예정입니다. 
- #171 
SecurityConfig에서 제가 놓친 부분이 있는지 확인해주세요.  
나중에 재구성은 해야할 것 같습니다. 같이 해봐요

[BE-#171] 로그인 시 사용자 권한 반환

---

backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLookupResponse.java
backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/test/java/com/ice/studyroom/domain/penalty/application/PenaltyServiceTest.java

- penalty 테이블에 reservation의 id 를 외래키로 추가
- 유저 정보 조회의 응답 데이터에 패널티 사유, 패널티 종료 기간을 추가해두었습니다.
#194 #
현재 패널티 이유는 영어로, 패널티 종료 시간은 별로도 파싱을 진행하지 않았습니다. 
프론트 측에서 약간의 변형이 필요합니다.

[BE-#194] 유저 정보 조회 응답 데이터, 패널티 데이터 추가

---

backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java

- RT를 HTTP secure 헤더를 통한 저장 및 Refresh API 호출 시 헤더로 전달 받게 수정
- HttpOnly 와 Secure Cookie를 활용하기
- 전달 받는 HTTP는 Cookie에 저장됩니다. 
- 예시: Set-Cookie: refresh_token=485e9a21-8d03-44b7-b4ce-e19551963aec; Path=/auth/refresh; Max-Age=604800; Expires=Wed, 19 Feb 2025 16:06:25 GMT; HttpOnly; SameSite=Strict
- #192 
확인해보시고 문의 사항 주세요:)

[BE-#192] RT를 헤더를 통해서 전달하도록 수정

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

- 연장 및 취소 페이지의 예약자명을 제대로 호출하고 안내 문구 예시를 삭제하였다.
- #262

[FE-#262] 연장 및 취소 페이지 예약자 오류 및 안내 문구 수정

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetReservationsResponse.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ParticipantResponse.java

- 개인 예약의 경우 본인의 정보만 확인하게 수정
```
public class ReservationService {
public List<GetReservationsResponse> getReservations(String authorizationHeader) {
// 코드 생략
// 최근 예약 가져오기
Optional<Reservation> recentReservation = reservationRepository.findFirstByUserEmailOrderByCreatedAtDesc(email);
// 최근 예약에서 scheduleId 추출 후 Schedule 조회
Schedule schedule = recentReservation
.map(Reservation::getFirstScheduleId) // scheduleId 가져오기
.flatMap(scheduleRepository::findById) // scheduleId로 조회
.orElseThrow(() -> new BusinessException(StatusCode.NOT_FOUND, "존재하지 않는 스케줄입니다."));
if (schedule.getRoomType().equals(RoomType.INDIVIDUAL)) {
return recentReservation
.map(reservation -> List.of(GetReservationsResponse.from(reservation, List.of()))) // 빈 리스트 반환
.orElseThrow(() -> new …
```

[BE-#300] 개인예약의 경우 개인 정보만 반환

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetReservationsResponse.java

- 가장 최근의 예약 정보만 받아오는 에러 발생
- 예약 정보가 없는 경우 에러 발생
```
Schedule schedule = scheduleRepository.findById(reservation.getFirstScheduleId())
.orElseThrow(() -> new BusinessException(StatusCode.NOT_FOUND, "존재하지 않는 스케줄입니다."));
if (schedule.getRoomType() == RoomType.GROUP) {
```
위 코드를 추가하여 Group 예약의 경우에만 참여자 정보를 담게 수정
- #308 

[BE-#308] 개인, 단체 예약 정보 모두 반환하게 수정

---

frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx

- mainpagehandler와 penaltyhandler 중 at를 사용하는 함수의 refreshtokens 호출을 catch문으로 이동했다.
- #341

[FE-#341] 토큰 재발급 함수 catch문으로 이동

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ReservationUpdateScheduler.java

- 예약 완료 처리 스케줄러가 예약 연장 여부를 확인하지 않은 부분을 수정했습니다.
- 패널티 여부를 우선적으로 확인하도록 개선했습니다.
- 동일 예약 조회 시, 스케줄 id를 활용하도록 했습니다.
- 다음 스케줄의 id가 이전 스케줄의 +1 인 점을 고려하여 다음 스케줄을 조회하도록 했습니다.
- 트랜잭션 어노테이션의 더티 체킹을 활용하였습니다.
- #352 

[BE-#352] 예약 연장 처리 로직 개선

---

backend/src/main/java/com/ice/studyroom/config/RedisConfig.java
backend/src/main/resources/application.properties

- redis비밀번호 설정
- 외부에서 EC2 IP와 Redis Port로 접근하여 Redis 복제를 시도하는 문제 해결 가능
- 복제를 시도함에 따라 Master Redis가 죽는 문제 해결 가능
- #373 
.env 업데이트 노션에 업로드 완료

[Chore-#373] redis 비밀번호 설정을 통안 보안 강화

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminOccupyRequest.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminReleaseRequest.java
backend/src/main/java/com/ice/studyroom/domain/admin/scheduler/RoomTimeSlotScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 관리자의 room_time_slot 선점,해지,조회 기능을 구현
- 당일 선점을 할 경우 schdule에 직접 업데이트 내용이 반영됩니다.
#395 

[BE-#395] 관리자 room_time_slot 선점, 해지, 조회 api 제작

---

backend/src/main/java/com/ice/studyroom/config/AppConfig.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ParticipantResponse.java
backend/src/test/java/com/ice/studyroom/domain/admin/application/AdminServiceTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java

대표 예약자 반환을 위한 is_holder 컬럼 추가 및 예약 조회 시 대표 예약자 반환  
예약 할 경우 대표 예약자는 대표 예약자로 구분  
**정상 취소**
- 입실 하기 60분 + 전에 취소 요청 했을 때  
**취소는 가능하지만 패널티 부여**
- 입실 하기 60분 전에 취소 요청 했을 때
- 입실 시간에 취소 요청 했을 때
**올바르지않은 접근**
- 예약한 아이디와 다른 아이디로 취소 요청 했을 때
- 존재하지 않는 예약 번호를 취소 요청 했을 때
**취소 불가능**
- 입실 취소가 지난 뒤에 취소 요청할 경우
```java
if (LocalDateTime.now().isAfter(startTime)) {
throw new BusinessException("입실 시간이 초과하였습니다.");
}
```
현재 비즈니스 로직에 현재 백엔드 어플리케이션의 시간에 의존하고 있기에 테스트에 용이하지않았습니다.  
따라서 Clock객체를 기반으로 개발자가 직접 시간을 설정할 수 있게하여 테스트를 용이하게 작성해주었습니다.  
```java
@Configuration
public class AppConfig {
@Bean
public Clock clock() {
return Clock.systemDefaultZone();
}
}
```
```java
@Transactional
public CancelReservationResponse cancelReservation(Long id, String authorizationHeader) {
// .. …
```

[Feature-#402, #403] 대표 예약자 반환 및 예약 취소 테스트 코드 작성 

---

frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 탭 상태를 저장하여 새로고침 해도 기존 탭이 유지되도록 변경했다.
- 선점 완료 및 해제시 새로고침을 통해 ui에 바로 업데이트 되도록 변경했다.
- #407

[FE-#407] 관리자 페이지 선점 완료, 해지시 ui 업데이트 및 탭 상태 저장

---

README.md
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java

- 테이블 정규화에 의한 점진적 개선을 하고 있습니다.
- 기존에 외래키로 등록되어있지않던 member 외래키를 등록해주었습니다.
- #410 
```java
public class Reservation {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
private Long id;
@ManyToOne(fetch = FetchType.LAZY)
@JoinColumn(name = "member_id")
private Member member;
/ .. 다른 코드
}
```
ManyToOne 관계로 지정해주었으며, 즉시로딩이 아닌 지연로딩으로 등록해서 N+1문제를 최소화 했습니다.  
프로젝트 전체적으로도 즉시로딩을 사용할 일은 없어보이니 추후에 추가될 외래키도 지연 로딩으로 부탁드리겠습니다.  
```
ALTER TABLE reservation
ADD COLUMN member_id BIGINT AFTER id;
ALTER TABLE reservation
ADD CONSTRAINT fk_reservation_member
FOREIGN KEY (member_id) REFERENCES member(id);
```
프로덕션 DB에 추가해주었습니다.  
이후 reservation 생성 시에 member를 등록해주었습니다.  

[BE-#410] reservation 테이블 스키마에 member 외래키 추가

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java

- 예약 조회, 예약 연장 삭제될 컬럼인(userName, userEmail) 의존성을 제거해주었습니다.
- #412 
```
public class Reservation {
// .. 다른 코드
public boolean isEntered() {
return status == ReservationStatus.ENTRANCE;
}
public boolean isOwnedBy(String rawEmail) {
return this.member.getEmail().equals(Email.of(rawEmail));
}
// .. 다른 코드
}
```
도메인에서 관리 가능한 메서드는 엔티티에 추가해주었습니다.  
```
if (nextSchedule.getRoomType() == RoomType.GROUP) {
// 그룹 예약 이기에 같은 시간대의 예약 레코드를 모두 가져온다(참여자 검증 필요). memeber 1차 캐시되며 이 값을 사용할 예정
List<Reservation> reservations = reservationRepository.findByFirstScheduleId(reservation.getFirstScheduleId());
// 그룹 예약 이기에 같은 시간대의 예약 레코드를 모두 가져온다(참여자 검증 필요). memeber 1차 캐시되며 이 값을 사용할 예정
List<Reservation> reservations = reservationRepository.findByFirstScheduleId(reservation.getFirstScheduleId());
// 패널티를 부여받고 있는 참여자가 …
```

[BE-#412] 예약 조회, 예약 연장 삭제 될 컬럼인(userName, userEmail) 의존성 제거 

---

backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java

- 개인 예약과 관련된 테스트 코드 작성
- #417 
- 비즈니스 로직에 강결합 되어있는 로직은 느슨하게 수정
- 테스트를 하기 위해 의존성 주입하기 어려운 코드가 존재합니다.
- 따라서 필요에 따라 결합을 느슨하게 만들기 위해 비즈니스 로직을 수정하고자 합니다.
- 단위 테스트를 최대한 많이 생성하여 테스트에 소요되는 시간 최소화
- 통합테스트에서는 단위테스트에 비해 많은 시간이 소요되기에 단위 테스트를 많이 생성해서 소요시간을 줄이고자 합니다.
- 다른 개발자가 보더라도 테스트 코드의 이유와 테스트 목표를 명확하게 명시
- 작성된 테스트 코드는 다른 개발자에게 비즈니스 로직의 목표를 제시해야합니다. 테스트 코드의 존재 이유를 다른 개발자에게 설득할 수 있어야합니다. 이를 위해 주석 추가와 함수명 한글 작성을 통해서 해결하고자 합니다.
- 경계값/예외 상황 테스트 포함
- 경계 값은 예외 케이스가 많이 발생할 확률이 큽니다. 저희 프로젝트는 시간에 따른 패널티 여부와 예약 성공 여부를 판별하기 때문에 시스템 정책에 맞는 비즈니스 로직이 수행되는지 확인해야합니다.
- 테스트 커버리지보다 "테스트 품질"을 우선
- 테스트 작성을 무의미한게 양산하게 된다면 테스트 코드의 가독성과 유지보수 또한 불편해집니다.
- 핵심 기능만을 간추려서 테스트 코드를 작성하려합니다.
- 정상적으로 스케줄을 예약 1시간 & 2시간
- 시간이 만료된 스케줄을 예약 1시간 & 2시간
- 잘못된 계정으로 예약을 시도한 경우
- 단체예약 전용 방을 개인 예약 시도하는 경우
- 예약 가능한 횟수가 오버부킹되는 경우
- 패널티 상태에서 …

[BE-#417] 개인 예약 테스트 코드 작성 및 비즈니스 로직 개선

---

backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ReservationUpdateScheduler.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
backend/src/test/java/com/ice/studyroom/helper/ReservationTestHelper.java

- Reservation 테이블의 userName, userEmali 컬럼 삭제 후 적용
- #425 
Reservation Entity의 userName, userEmail 제거 후 완전한 member 사용으로 수정해주었습니다.  
정상적으로 테스트 코드를 통과했으며, 비즈니스 로직 또한 QA도 정상적으로 돌아가는 것을 확인했습니다.

[BE-#425] 예약 API, 패널티 API에 삭제될 컬럼에 대한 종속성 삭제 및 개선

---

backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java

- 예약 조회 API 호출 시 fetch가 되지 않는 오류 확인
- #427 
```
failed to lazily initialize a collection of role: Member.roles
could not initialize proxy - no Session
```
위의 에러 로그 발생  
이는 Member 엔티티에 외래키인 role 컬럼의 지연로딩이 JPA 세션이 종료되었는데도 직렬화를 시도하는데서 발생한 오류임을 확인
따라서
```
@ElementCollection(fetch = FetchType.LAZY)
@CollectionTable(
name = "user_roles",
joinColumns = @JoinColumn(name = "user_id")
)
@Column(name = "role", nullable = false)
@JsonIgnore
private List<String> roles = new ArrayList<>();
```
위와 같이 JsonIgnore로 처리해주어 직렬화가 무시되게 처리  
JWT에서 이미 userRole을 추출하기 때문에 직렬화 무시 처리해도 비즈니스 로직은 정상적으로 작동합니다.

[BE-#427] 지연로딩에 따른 UserRole 직렬화 실패 오류 수정

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/QrEntranceRequest.java

- QR 토큰을 클라이언트로부터 전달받는 로직으로 변경됨애 따라 코드 수정
- #434  
```
public class ReservationService {
// .. 코드 생략
@Transactional
public QrEntranceResponse qrEntrance(QrEntranceRequest request) {
// 클라이언트로부터 전달된 토큰 저장
String token = request.qrToken();
// 토큰으로 예약 ID 조회
Long reservationId = qrCodeService.getReservationIdByToken(token);
if (reservationId == null) {
throw new BusinessException(StatusCode.BAD_REQUEST, "만료되었거나 유효하지 않은 QR 코드입니다.");
}
// .. 코드 생략
}
}
```
입실 API에 전달되는 클라이언트 DTO의 값이 이미지가 아닌 토큰으로 수정되었기에 토큰으로 변경해주었습니다.

[BE-#434] 입실 API 요청 값을 QR 코드가 아닌 QR 토큰 전달로 수정

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/QrEntranceResponse.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrEntranceTest.java

- QR 입실 로직 테스트 코드 작성
- QR 입실 API 응답 객체 Record로 개선
- @Getter, @AllArgsConstructor 없어도 자동으로 생성자, getter, toString(), equals(), hashCode() 제공됨
- 필드는 자동으로 private final로 선언됨 (불변 객체)
- #452 
```
public record QrEntranceResponse(
ReservationStatus status,
String userName,
String userNumber
) {}
```
record는 이 프로젝트를 시작하면서 처음 접한 객체 타입인데 아래와 같은 도움을 줍니다.  
- @Getter, @AllArgsConstructor 없어도 자동으로 생성자, getter, toString(), equals(), hashCode() 제공됨
- 필드는 자동으로 private final로 선언됨 (불변 객체)  
예약 도메인은 초기에 작성되었기에 일부 코드가 Class로 처리되어있습니다.  
나중에 직접 바꿔보시면서 한번 효율성은 느껴보시죠..!
```
public ReservationStatus checkAttendanceStatus(LocalDateTime now) {
LocalDateTime startDateTime = LocalDateTime.of(scheduleDate, startTime);
LocalDateTime endDateTime = LocalDateTime.of(scheduleDate, endTime);
if …
```

[BE-#452] QR 입실 테스트 코드 작성

---

backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetMostRecentReservationResponse.java

- 최근 예약 기록 확인 API 응답에 시작시간, 종료시간 추가
- #455 
```java
public record GetMostRecentReservationResponse(
LocalDate scheduleDate,
String roomNumber,
LocalTime startTime,
LocalTime endTime
) {
public static GetMostRecentReservationResponse from(Reservation reservation) {
return new GetMostRecentReservationResponse(
reservation.getScheduleDate(),
reservation.getRoomNumber(),
reservation.getStartTime(),
reservation.getEndTime()
);
}
}
```
예약 시작 시간, 종료 시간을 추가해주었습니다.

[BE-#455] 최근 예약 기록 확인 API 응답에 시작시간, 종료시간 추가

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/domain/util/AdminLogUtil.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/util/MembershipLogUtil.java
backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/service/PenaltyDomainService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/util/PenaltyLogUtil.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/util/ReservationLogUtil.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/GroupReservationTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java

- 도메인 전반의 로깅 메시지를 통일된 포맷으로 개선하고, 로깅 유틸리티 클래스를 적용
- 불필요한 중복 로그 제거 및 로그의 의미 명확화를 통해 유지보수성과 지표 수집 효율성을 향상
- 예약/패널티/회원/관리자 서비스 내 주요 로직 수행 시점에 통일된 로그 메시지를 출력하도록 변경
#478 
- ReservationLogUtil, PenaltyLogUtil, MemberLogUtil, AdminLogUtil 도입
- 금일 패널티 부여 수, 패널티 사유별 비율 등 로그 기반 지표 수집을 위한 메시지 포맷 개선
- 각 서비스에 로깅 유틸 적용 완료 (ReservationService, PenaltyService, MembershipService, AdminService 등)
- LogQL 기반 지표 대시보드 구축을 위한 로그 구조 기반을 위한 작업입니다.
- 로그를 작성하면서, 비즈니스 로직에서 조회하는 순서가 바뀌었습니다. 그로인해 테스트 코드에 변경이 있습니다.

[BE-#478] 서비스 로깅 메시지 통일 및 유틸리티 적용

---

backend/src/main/java/com/ice/studyroom/IceStudyRoomApplication.java
backend/src/main/java/com/ice/studyroom/domain/identity/domain/SecurityUser.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/encrypt/PasswordEncryptor.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/encrypt/PasswordEncryptorImpl.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/manage/MemberEmailService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/manage/MemberPasswordService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/EncodedPassword.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/RawPassword.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/GroupReservationTest.java

- 비밀번호를 값 객체로 변환함에 따른 자기 유효성 검사 가능 및 비즈니스 로직 간소화
- MemberPasswordService, MemberEmailService, PasswordEncryptor 과 같은 도메인 레이어를 구현함에 따른 객체 간의 협력 레이어 구현
- 어플리케이션 레이어는 흐름만 작성하도록 수정
- 도메인 서비스 메서드 명을 어플리케이션애서 사용하는데 있어 개발 생산성을 늘리기 위해 메서드 컨벤션 설정
- #484 
현재 비밀번호 검증은 DTO에서만 Valid로 검증되고 있습니다. 다만 비즈니스 로직에서 생성되는 email이나 데이터는 검증되지않은 채로 생성될 수 있다는 위험이 있습니다.
따라서 비밀번호 VO를 생성해서 유효성 검증이 가능하며 더 나아가 Entity에 컬럼으로 적용될 수 있게 하였습니다.
비밀번호는 평문과 암호문 이렇게 2개의 상태가 존재합니다.
비밀번호 유효성 검증은 오직 평문인 상태에서만 검증이 가능합니다. 그러나 우리가 직접 데이터 베이스에 저장하는 데이터는 암호화된 비밀번호입니다. 이에 따라 비밀번호 VO를 암호화 여부에 따른 데이터로 구분했습니다.
따라서 유효성 검증 및 비밀번호 비교는 RawPassword가 관리합니다.
```java
@NoArgsConstructor(access = AccessLevel.PROTECTED)
public class RawPassword {
@Column(name = "password", nullable = false)
private String value;
private RawPassword(String value) { …
```

[BE-#484] Membership 도메인의 이메일, 비밀번호 비즈니스 로직 분리 및 VO를 활용한 자기 유효성 검사 구현

---

backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

-  2시간의 예약을 진행했을경우, 종료 시간이 1시간의 예약만 반영되었던 버그를 수정했습니다.
- 로그인 실패 메시지가 상세한 것 같습니다. (회원가입 로직과 동일) 그래서 에러메시지를 우선 `아이디 혹은 비밀번호가 일치하지 않습니다.` 로 수정해두었습니다. 
- #486 

[BE-#486] 이메일 예약 이용 시간 버그 수정

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/domain/service/manage/RoomModificationService.java
backend/src/main/java/com/ice/studyroom/domain/admin/domain/service/policy/RoomPolicyService.java
backend/src/main/java/com/ice/studyroom/domain/admin/infrastructure/persistence/RoomTimeSlotRepository.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminModRoomTypeRequest.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/RoomInfoResponse.java
backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/ice/studyroom/global/exception/RoomNotFoundException.java
backend/src/main/java/com/ice/studyroom/global/exception/jwt/RoomNotFoundException.java

- 이제 관리자가 프론트를 통해 특정 방의 '단체 예약' 과 '개인 예약' 을 직접 변경할 수 있습니다.
- #490 
```java
@RestController
@RequiredArgsConstructor
@RequestMapping("/api/admin")
public class AdminController {
private final AdminService adminService;
// 코드 생략
@Operation(
summary = "방의 RoomNumber, RoomType, capacity 정보 조회",
description = "방의 RoomNumber, RoomType, capacity 정보 조회를 할 수 있습니다." +
"모든 요일의 방을 정보를 전달해주는 것이 아닌 방 번호 기준으로 전달됩니다."
)
@ApiResponse(responseCode = "200", description = "요일 구분없이 방에 대한 정보 조회 성공")
@ApiResponse(responseCode = "500", description = "요일 구분없이 방에 대한 정보 조회 성공")
@GetMapping("/rooms")
public ResponseEntity<ResponseDto<List<RoomInfoResponse>>> getRoomInfo() {
return ResponseEntity
.status(HttpStatus.OK)
.body(ResponseDto.of(adminService.adminGetRoomInfo()));
}
@Operation(
summary = "방의 RoomType(예약 단위) …
```

[BE-#490] 관리자의 방 정보 조회 및 방 타입 변경 기능 구현

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationCompensationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationConcurrencyService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/service/ReservationValidator.java
backend/src/main/resources/application.properties
backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrEntranceTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/concurrency/IndividualReservationOverBookingTest.java

- 트랜잭션을 분리하여 락 조회 시 정상적으로 새로운 트랜잭션이 적용되게 구현
- 항상 정렬된 Schedule을 접근하여 데드락이 발생하지않게 변경
- 외부 트랜잭션 실패 시 수행하는 보상 트랜잭션 구현 및 추가
- #500 
```bash
2025-07-11 18:04:43.629 [http-nio-0.0.0.0-8080-exec-1] INFO  c.i.s.d.m.d.util.MembershipLogUtil - [MEMBERSHIP] 로그인 요청 - [email: glaxyt@hufs.ac.kr] [requestId=24d84364-66ce-4410-8a60-878f27e7771b, userEmail=]
2025-07-11 18:04:44.134 [http-nio-0.0.0.0-8080-exec-1] INFO  c.i.s.d.m.d.util.MembershipLogUtil - [MEMBERSHIP] 로그인 성공 - [email: glaxyt@hufs.ac.kr] [requestId=24d84364-66ce-4410-8a60-878f27e7771b, userEmail=]
2025-07-11 18:05:06.646 [http-nio-0.0.0.0-8080-exec-3] INFO  c.i.s.d.r.a.ReservationService - [createIndividualReservation] txActive = true, txName = com.ice.studyroom.domain.reservation.application.ReservationService.createIndividualReservation …
```

[BE-#500] 개인 예약, 그룹 예약 락 서비스 로직 수행 간에 발생하는 문제 해결

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/reservation/InvalidEntranceAttemptException.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/reservation/InvalidEntranceTimeException.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/reservation/InvalidReservationCreationException.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/reservation/QrIssuanceNotAllowedException.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/reservation/ReservationAccessDeniedException.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/type/InvalidEntranceAttemptReason.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/type/InvalidEntranceTimeReason.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/type/QrIssuanceErrorReason.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/exception/type/ReservationAccessDeniedReason.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/redis/QRCodeService.java
backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/ice/studyroom/global/exception/token/InvalidQrTokenException.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/GetMyReservationQrCodeTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/IndividualReservationTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationExtendTest.java

- QR 코드 발급 및 입실 파이프라인 코드 개선
- QR 코드 발급 이후 15분 간 유지되던 로직 삭제 -> 24시간 유지로 변경
- 사유: 사용자 편의성을 위해서 24시간으로 변경
- 응용 서비스 로직에 노출되어있는 논리적 행위를 엔티티에서 수행하도록 책임 이양
- 로깅 코드와 비즈니스 로직이 혼재되어있는 코드 문제 개선
- 전역 예외처리에서 로깅하는 방식으로 변경
- 응집력이 향상된 코드 및 응용 계층 가독성 향상 기대
- #504 
- [] 모든 테스트가 통과하나요?
```java
/**
* Reservation.status 가 RESERVED 이외의 상태일 경우 QR을 발급 받을 수 없습니다.
* 위의 경우 QR을 발급받으려고 할 경우 발생하는 예외입니다.
*/
public class InvalidEntranceAttemptException extends BusinessException {
private final Long reservationId;
public InvalidEntranceAttemptException(InvalidEntranceAttemptReason reason, Long reservationId) {
super(StatusCode.BAD_REQUEST, reason.getMessage());
this.reservationId = reservationId;
}
public Long getReservationId() {
return reservationId;
}
}
```
- reservationId를 영속성 객체로부터 전달 받아 전역 예외 처리에서 로깅하도록했습니다
- …

[BE-#504] QR 발급 및 입실 파이프라인 코드 개선

---

backend/src/main/java/com/ice/studyroom/domain/membership/domain/exception/member/MemberNotFoundException.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/schedule/application/ScheduleService.java
backend/src/main/java/com/ice/studyroom/domain/schedule/domain/exception/schedule/ScheduleNotFoundException.java
backend/src/main/java/com/ice/studyroom/domain/schedule/infrastructure/redis/ScheduleVacancyAlertService.java
backend/src/main/java/com/ice/studyroom/domain/schedule/presentation/ScheduleController.java
backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java
backend/src/main/java/com/ice/studyroom/global/type/ActionType.java

- 빈자리 알림 등록 서비스를 구현합니다.
- 사용자가 알림 등록을 할 수 있게 API를 호출할 수 있게합니다.
- 사용자의 정보는 Redis에 저장됩니다.
- 저장 구조는 예시는 아래와 같습니다.
- "vacancy-notification:schedule:11": { "glaxyt@hufs.ac.kr" : "도성현", "example@hufs.ac.kr": "심재성" }
- "vacancy-notification:schedule:11"의 11은 scheduleId를 뜻합니다.
- 이 정보는 추후에 빈자리가 발생하면 카프카를 통해서 전달됩니다.
- #507 
- POST "/api/schedules/{scheduleId}/vacancy-alert" + AccessToken
- Body는 없습니다. 오직 쿼리 파라미터와 AccessToken만으로 수행이 가능합니다.
```java
@Service
@RequiredArgsConstructor
public class ScheduleVacancyAlertService {
private final RedisTemplate<String, Object> redisTemplate;
private static final String REDIS_KEY_PREFIX = "vacancy-notification:schedule:";
/**
* 특정 스터디룸에 대한 빈자리 알림을 신청합니다.
* @param scheduleId 알림을 받을 스케줄 ID
* @param email 알림을 받을 사용자의 이메일
* @param userName 알림을 받을 사용자의 이름
*/
public …
```

[BE-#507] 빈자리 알림 등록 API 구현
