ICE-STUDYRES/ice-studyroom

.gitignore
backend/build.gradle
backend/src/main/java/com/ice/studyroom/config/SecurityConfig.java
backend/src/main/java/com/ice/studyroom/config/SwaggerConfig.java
backend/src/main/java/com/ice/studyroom/domain/reservation/api/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dao/ScheduleRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ScheduleStatus.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dto/request/CreateReservationRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dto/request/CreateScheduleRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dto/request/DeleteReservationRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dto/response/ReservationResponse.java
backend/src/main/java/com/ice/studyroom/domain/reservation/dto/response/ScheduleResponse.java
backend/src/main/java/com/ice/studyroom/domain/room/api/RoomScheduleController.java
backend/src/main/java/com/ice/studyroom/domain/room/dao/RoomRepository.java
backend/src/main/java/com/ice/studyroom/domain/room/dao/TimeSlotRepository.java
backend/src/main/java/com/ice/studyroom/domain/room/domain/entity/Room.java
backend/src/main/java/com/ice/studyroom/domain/room/domain/entity/TimeSlot.java
backend/src/main/java/com/ice/studyroom/domain/user/domain/entity/User.java
backend/src/main/java/com/ice/studyroom/global/entity/BaseTimeEntity.java
backend/src/main/resources/application.properties
backend/src/test/java/com/ice/studyroom/IceStudyRoomApplicationTests.java
backend/src/test/java/com/ice/studyroom/domain/reservation/api/ReservationControllerTest.java

- #2 
[DDL 수정본 링크](https://ballistic-dragon-6f2.notion.site/ERD-16c7d6c84c71800abc8fcfc3056c2bff?pvs=4)

[BE -#2] 예약 생성, 취소 API 구현

---

frontend/fr-study/src/pages/Reservation/BookingContext.jsx
frontend/fr-study/src/pages/Reservation/Infoinput.css
frontend/fr-study/src/pages/Reservation/Infoinput.jsx
frontend/fr-study/src/pages/Reservation/RoomSelection.css
frontend/fr-study/src/pages/Reservation/RoomSelection.jsx
frontend/fr-study/src/pages/Reservation/TimeSelection.css
frontend/fr-study/src/pages/Reservation/TimeSelection.jsx

[FE -#] 예약 페이지 생성

---

frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.css
frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx

[FE -#] 예약현황 페이지 생성

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/JwtToken.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberCreateResponse.java

회원가입 기능을 추가하였습니다. 또한 인증 인가 기능을 위해서 JWT를 사용하고 있습니다.
인증 인가 기능이 추가되었기에 이에 맞춰서 SecurityConfig를 수정하여 적용했습니다.
- #29 

[BE -#29] 회원가입 구현 및 인증 인가 설정

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/SecurityUser.java
backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/CustomUserDetailsService.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberLoginRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java

로그인이 가능하면 인증 인가를 위한 토큰을 발급합니다.
- #32 

[BE -#32] 로그인 구현 및 인증 인가를 위한 토큰 반환

---

frontend/fr-study/src/App.jsx
frontend/fr-study/src/pages/Mainpage/mainpage.jsx

기존의 로그인 상태를 저장하지 않던 문제를 해결하고, 로그인 했을 때만 페이지 이동이 가능하도록 수정
QR코드 캔버스 및 QR코드 생성
- #36 #37

[FE -#36, 37] 로그인 상태 저장 및 QR코드 생성

---

backend/build.gradle
backend/src/main/java/com/ice/studyroom/config/RedisConfig.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/resources/application.properties
backend/src/test/java/com/ice/studyroom/config/RedisConnectionTest.java

Redis 환경 설정 및 연결을 했습니다.
테스트 코드를 통해서 연결이 되는 것을 확인했습니다.
- #49 

[BE -#49] Redis 환경설정 및 연결

---

backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java

[hotfix] 엔티티 매핑 버그 수정

---

backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/response/MemberLoginResponse.java

Access토큰을 헤더로 전달할 수 있게 API 수정
- #60 

[BE -#60] Access 토큰 헤더로 변경

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/vite.config.js

로그인, 회원가입 api 연동 과정 중 CORS 이슈가 발생해서 proxy로 해결했다.
#39

[FE -#39] 로그인, 회원가입 API 연결

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateScheduleRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/DeleteReservationRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ReservationResponse.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ScheduleResponse.java
backend/src/test/java/com/ice/studyroom/domain/reservation/presentation/ReservationControllerTest.java

전체 스케줄 조회와 Access Token을 통한 내 예약 확인하기가 가능해졌다.
- #63 
API 명세서 업데이트 완료

[BE -#63] 내 예약 확인하기 및 전체 스케주 조회 구현

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/vite.config.js

로그인, 로그아웃, 회원가입 api 연동을 했다.
#39

[FE -#39] 회원가입, 로그인, 로그아웃 api 연결

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/presentation/ReservationControllerTest.java

최소인원 컬럼 & 사용자 이름 모킹 코드 추가
- 없음

[BE] 최소인원 컬럼 추가 및 사용자 이름 모킹

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx

[FE -#69] 메인페이지 ui, 핸들러 컴포넌트 분리

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx

인증번호 전송을 위한 버튼을 생성하고 인증번호 확인을 위한 텍스트박스를 생성했다.
#74

[FE-#74] 이메일 인증, 확인 텍스트박스 및 버튼 생성

---

frontend/fr-study/src/App.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx
frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx

전체 스케줄 조회 기능 구현
내 예약조회 페이지 생성 및 qr 이동
#66

[FE -#66] 예약 확인 기능 구현

---

backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
backend/src/main/resources/application.properties
backend/src/test/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTaskTest.java

- 월-금 새벽 3시마다 스케줄을 자동생성해주는 스케줄러를 구현했습니다.
- #80 
이미지는 테스트를 위해서 실행된 것이기에 3시 8분으로 설정되어있음, PR된 코드는 3시로 수정했음.
또한 테이블에 오늘 날짜로 오늘 요일의 데이터가 들어오는 것을 확인

[BE -#80] 스케줄 자동 생성 스케줄러 구현

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/VerificationCodeCacheService.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/email/EmailVerificationService.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
backend/src/test/java/com/ice/studyroom/domain/membership/infrastructure/email/EmailVerificationServiceTest.java

이메일 인증 여부를 반응한 회원가입 요청 dto를 업데이트 했습니다.
api 명세서 참고해주시면 감사하겠습니다!
#76 

[BE -#76] 회원가입 요청 dto 업데이트

---

backend/src/main/java/com/ice/studyroom/domain/identity/exception/InvalidJwtException.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/entity/Member.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/MembershipController.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/TokenRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/UpdatePasswordRequest.java
backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/entity/RoomTimeSlot.java

- 로그인한 상태에서 비밀번호 변경이 가능합니다.
- Access Token 반환이 만료될 경우 401을 반환합니다.
- #30, #90 

[BE-#30, #90] 비밀번호 수정 구현 및 AccessToken 만료 확인

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminCreateOccupyRequest.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminDeleteOccupyResponse.java
backend/src/main/java/com/ice/studyroom/domain/room_timeslot/domain/entity/RoomTimeSlot.java
backend/src/main/java/com/ice/studyroom/domain/room_timeslot/infrastructure/persistence/RoomTimeSlotRepository.java

관리자 선점 목록 조회 및 선점 해지 기능 구현했습니다.
자세한 사항은 API 명세서 확인 부탁드립니다.
(#86)

[BE-#86]  관리자 선점 목록 조회 및 선점 해지 기능

---

frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx

방별로 예약 현황을 잘 볼 수 있도록 함수 및 html코드를 수정했다.
#97

[FE -#97] 전체 예약 조회 페이지 수정

---

backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/GetMostRecentReservationResponse.java

- 최근 예약 1건을 조회할 수 있습니다.
- #107 

[BE-#107] 최근 예약 조회하기

---

backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java

- Refresh API 반환 오류 수정
- 이제 정상적인 토큰 재발급이 됩니다.
- #111 

[BE-#111] RT 반환 오류 수정 및 예약 DDL 추가 

---

frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomBookingUI.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- 기존 RT 방식에서 RTR방식으로 변경했다.
- #115

[FE - #115] RTR 토큰 관리 기법 적용

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- ui의 불필요한 요소를 제거하고 하드코딩 된 부분은 데이터를 불러온다.
- 내 예약현황의 최신 예약이 가장 위로 올라오게 한다.
- #119 #122

[FE - #119, 122] 메인페이지 ui 수정 및 예약현황 순서 업데이트

---

frontend/fr-study/src/pages/Mainpage/QRCodeFetcher.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- QR코드를 불러오고 내 예약 현황에서 볼 수 있게 표시함
- #120 

[FE-#120] 예약자 QRCode 불러오기 및 출석 요청

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
frontend/fr-study/src/pages/Mainpage/ProfileDropdown.jsx

- 비밀번호 변경 기능을 구현하고, 이에 따라 ui도 조정하였다.
- #116

[FE - #116] 비밀번호 변경 기능 구현

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx

- 최근 예약을 불러오는 기능을 api와 연결하였다.
- #132

[FE - #132] 최근 예약 불러오기 api 연동

---

frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- 내 예약이 최신 순으로 나열이 안되어있던 문제가 있어 변경했다.
- #122

[FE - #122] 내 예약 최신 순 나열

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java

1. 개인 예약 생성 기능 추가
2. 단체예약시 현재 사용인원 반영 리팩토링
(#138)

feat: 개인예약 생성 기능

---

frontend/fr-study/src/pages/Mainpage/QRCodeFetcher.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

[FE- #142] QR코드 스캔 및 출석요청 구현

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/ReservationController.java

1. 예약 시 패널티 여부 및 최근예약상태 검사 추가
2. 단체예약 api reservation -> reservation/group 으로 변경
3. 정상퇴실확인 상태 추가
(#136)

[BE-#136] 개인/단체 예약 패널티 여부 및 최근예약상태 조회

---

frontend/fr-study/package.json
frontend/fr-study/pnpm-lock.yaml

- 의존성 파일을 제대로 업로드 하지 않아서 현재 설치할때 버전이 달라지는 문제가 발생해서 해결하려고 합니다.
- #153 

[FE - #153] 의존성 설치파일 추가

---

frontend/fr-study/package.json
frontend/fr-study/pnpm-lock.yaml
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- QR코드 중복으로 인코딩 되는 문제 해결
- #155 

[FE-#155] QR코드 중복 인코딩 문제 해결

---

frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- api 변동에 따라 코드를 수정하였다.
- #160

[FE - #160] api 수정에 따른 코드 수정

---

frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx

- 예약자 명은 표시하지 않고, 참여 인원을 올바르게 받아오도록 변경하였다.
- #123

[FE - #123] 데이터 호출 수정

---

frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx

- 하드코딩된 데이터 수정하고, 취소 기능 구현
- #137

[FE - #137] 데이터 호출 및 취소 기능 구현

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/domain/entity/RoomTimeSlot.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminPenaltyRequest.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyControlResponse.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/vo/Email.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateReservationRequest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java

- 중복 예약 오류 수정
- admin 패널티 부여 함수 수정
- 예외 처리 BusinessException 로 통일
#150  #152 #158 

[BE - #150 #152 #158] 중복 예약 예외처리, admin 패널티 개선, BusinessException 통일

---

frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx

[FE - #163] 연장하기 기능 구현

---

frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx

- 단체예약과 개인예약 api를 분리했다.
- #166

[FE - #166] 단체, 개인예약 기능 업데이트

---

backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/global/entity/BaseTimeEntity.java

- 예약 취소 시 발생하는 오류를 수정했습니다. penalty 속성의 create, update 가 자동으로 반영이 안되어 발생하는 오류였습니다.
- BaseTimeEntity 에 @PrePersist @PreUpdate 의 메서드를 추가하여 빌더 사용 시 해당 값이 자동으로 설정되도록 수정하였습니다.
#168 

[BE - #168] 예약 취소 오류 수정

---

frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- resId를 올바르게 불러오지 못해서 QR코드를 불러오고 출석체크가 안됐던 문제 해결
- #172 

[Fix] QR코드 출석체크 오류 수정

---

frontend/fr-study/src/pages/ReservationStatus/ReservationStatus.jsx

- 개인방도 예약 현황이 잘 보이도록 수정했다.
- #174

[FE - #] 전체예약조회 개인방 표기 오류 수정

---

frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomBookingUI.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

-  Current_res를 통해 개인 예약시 잔여 좌석 표시와 개인과 단체방 구별 UI 구현
- #179 

[FE-#179] 잔여좌석 및 개인과 단체방 구별 UI&기능 구현

---

frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx

- 예약이 없을 때 연장/취소 페이지 화면을 별도로 생성했다.
- #176

[FE - #176] 진행 중인 예약 없을 때 연장/취소 페이지 화면 수정

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/Mainpage/ProfileDropdown.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx

- AccessToken을 사용하는 함수들에 토큰 재발급 기능을 적용시켰다.
- #180

[FE - #180] AccessToken 사용 함수 토큰 재발급 적용

---

frontend/fr-study/package.json
frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx

- 패널티 현황을 한 눈에 볼 수 있도록 ui를 수정했다.
- 불필요한 요소 제거(홈버튼 클릭시 불필요한 navigate->새로고침)
- 유의사항에 스터디룸 이용 규칙, 패널티 관련 규칙 병합
- 모바일 기기에서 접속할 수 있도록 서버 설정 변경
- #188

[FE - #188] 메인페이지 ui 수정 및 하드코딩 제거

---

frontend/fr-study/src/App.jsx
frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
frontend/fr-study/src/pages/Mainpage/QRCodeFetcher.jsx
frontend/fr-study/src/pages/Notification/Notification.jsx
frontend/fr-study/src/pages/Notification/NotificationMessage.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomBookingHandler.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomBookingUI.jsx
frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- Alert방식에서 Toast Message로 변경되고 관련된 컴포넌트에 모두 적용하였습니다.
- #198 

[FE-#198] Alert to Toast Message로 변경 후 구현

---

frontend/fr-study/src/pages/Mainpage/Mainpage.jsx
frontend/fr-study/src/pages/Mainpage/MainpageHandlers.jsx
frontend/fr-study/src/pages/ReservationStatus/MyReservationStatus.jsx

- 메인페이지에 패널티 상태를 업데이트하고, 내 예약 페이지에 방 상태를 업데이트했다.
- #196 #197

[FE-#196,197] 패널티 api 연결 및 내 예약 조회 방 상태 업데이트

---

frontend/fr-study/src/pages/Reservation/StudyRoomManage.jsx

- 예약 취소시 연장 및 취소 페이지에 안보이게 한다.
- #200

[FE-#200] 예약 취소시 연장페이지에서 제거

---

frontend/.github/workflows/deploy.yml
frontend/vite.config.js

- S3+ cloudfront 사용해서 설정하고 deploy.yml파일 추가했습니다.
- #209 

[FE-#209] 프론트엔드 자동배포 설정 파일

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java

- 중복체크 예약상태 취소한 반환메시지 수정
(#190)

[BE-#190] 반환 메시지 수정

---

backend/src/main/resources/application.properties

- server port, address 속성 추가
- #213 

[BE-#213] server port, address 속성 추가

---

backend/src/main/java/com/ice/studyroom/config/CorsConfig.java

[BE-#215] CORS 설정 추가

---

backend/src/main/java/com/ice/studyroom/config/CorsConfig.java

[hotfix] cors 설정 충돌 해결

---

frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/MainpageHandlers.jsx
frontend/src/pages/Mainpage/MemberHandlers.jsx
frontend/src/pages/Mainpage/PenaltyHandlers.jsx
frontend/src/pages/Mainpage/Popups.jsx
frontend/src/pages/Mainpage/TokenHandler.jsx
frontend/src/pages/Reservation/StudyRoomBookingHandler.jsx
frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

[FE-#219] 프론트엔드 파일 리팩토링

---

frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
frontend/src/pages/ReservationStatus/ReservationStatus.jsx

- 로그아웃 기능이 없던 페이지들에 로그아웃 기능을 추가했다.
- #224

[FE-#224] 로그아웃 기능 추가

---

backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Schedule.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/request/CreateScheduleRequest.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/ScheduleResponse.java

1. schedule entity에 dayOfWeekStatus 추가(column, builder, from)
2. 관련 request, response dayOfWeekStatus 추가

hotfix: schedule entity dayOfWeekStatus 추가

---

frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
frontend/src/pages/Reservation/handlers/userInfomanager.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

- accesstoken을 저장하는 곳을 기존 local storage에서 sesssion storage로 바꿨다.
- #223

[FE-#223] 토큰 저장 방식 변경

---

backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java

- 가입되지 않은 이메일로 로그인 시 예외처리가 되도록 수정했습니다.
#232 

[BE-#232] 가입되지 않은 이메일로 로그인 시 예외처리

---

frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx

[Hotfix] 참여자 정보 추가 오류 수정

---

.github/workflows/deploy-server.yml

- cd코드 실행 시 docker 의 시간을 한국 시간으로 설정하도록 했습니다.
#236 

[BE-#236] cd코드 실행 시 docker 한국 시간 설정

---

frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/components/Popups.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- 비밀번호 설정시 특수문자 포함
- 인증코드 발송 후 남은시간 표기
- 회원가입 완료시 팝업 닫기
- #238

[FE-#238] 회원가입 관련 기능 개선

---

backend/src/main/java/com/ice/studyroom/config/CorsConfig.java

[hotfix] cors http 메소드 추가

---

frontend/src/pages/Mainpage/components/Popups.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- 비밀번호 변경시 특수문자를 포함하도록 한다.
- #241

[FE-#241] 비밀번호 변경 특수문자 추가

---

backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/QrController.java
backend/src/main/java/com/ice/studyroom/domain/reservation/presentation/dto/response/QrEntranceResponse.java
backend/src/main/resources/application.properties

- QR 응답 완료 시, 이름 학번 같이 주기
- 스케줄 동작 시간 6시로 변경하기
- [회원 가입] 적절하지 않은 학번 / 중복된 학번으로 회원가입을 요청
- [회원 가입] 특수문자가 없는 비밀번호로 회원가입을 시도
- [로그인] 이메일이나 비밀번호가 틀린 로그인 요청
#244 

[BE-#244] 테스트 시나리오 1차 점검

---

backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/UpdatePasswordRequest.java

- 테스트 기간에는 일시적으로 비밀번호 규칙을 무효화하도록 하겠습니다.

[hotfix] 비밀번호 규칙 무효화

---

backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java

- 패널티 스케줄러 버그 수정
- 패널티 종료 일자가 +1일 되는 버그 수정
#251 

[Fix-#251] 패널티 종료 일자, 스케줄러 버그 수정

---

backend/src/main/resources/application.properties

- 스프링 서버 시간을 KST 시간으로 설정하였습니다.

[hotfix] spring 서버 시간 설정 추가

---

frontend/src/pages/ReservationStatus/ReservationStatus.jsx

- 하드코딩을 제거하고, 불필요하게 예약현황을 병합하고 있던 코드를 제거한다.
- #243

[FE-#243] 전체 예약 현황 페이지 수정

---

backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java

- 패널티 스케줄러 발생 오류 수정
LocalTime 과 LocalDate를 LocalDateTime 으로 강제로 변환하는 과정에서 발생한 오류로 추정

[hotfix] 패널티 스케줄러 오류 수정

---

frontend/src/pages/Reservation/handlers/roomBookingManager.jsx

- 어떤 변경사항이 있는지 설명해주세요.
- #256 

[FE-#256] TimeSlot의 예약 가능한 시간 로직 변경

---

frontend/src/App.jsx
frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/components/Popups.jsx
frontend/src/pages/Mainpage/components/Signin.jsx
frontend/src/pages/Mainpage/components/Signup.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- isloggedin 제거
- 로그인 페이지 생성
- 로그아웃 페이지 생성
- 로그인시 role에 기반하여 페이지 이동
- #258

[FE-#258] 메인페이지 수정

---

frontend/src/App.jsx
frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
frontend/src/pages/Mainpage/Adminpage/PenaltyManagement.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 어드민 패널티 관리와 예약 선점 관리 페이지 구현
- #260 

[FE-#260]하드코딩과 목업만 작성해놓은 어드민 페이지 구현

---

backend/src/main/java/com/ice/studyroom/domain/penalty/domain/entity/Penalty.java
backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java

- updateMemberPenalty 패널티 해제 스케줄러 함수를 개선했습니다.
- processNoShowPenalties 노쇼 패널티 부여 스케줄러 함수 개선 및 오류 수정했습니다.
- #251 
노쇼 스케줄러 로컬에서는 잘 동작되는데 왜 서버에서는 안될까요.. 제발 되길

[BE-#251] 패널티 부여, 해제 스케줄러 로직 수정

---

frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
frontend/src/pages/Reservation/StudyRoomManage.jsx

- 사용하지 않는 변수 islogged인때문에 페널티 데이터를 호출하지 않던 상태였다. accesstoken으로 변경하여 api요청을 제대로 하도록 변경했다.
- #265

[FE-#265] 페널티 ui 오류 수정

---

backend/Dockerfile
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java

[hotfix] docker 한국 시간 설정 추가

---

backend/Dockerfile
backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java

- 영속성 컨텍스트에 resevation이 포함되도록 조정

[hotfix] 노쇼 스케줄러 버그 수정

---

backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/QrRecognitionServiceTest.java

- 예약 상태를 판별하는 함수와 상태를 업데이트 함수를 분리
- `@transactional` 선언 함수 내부에서 상태 업데이트 함수를 호출하여 더티 체킹 보장
#272 

[BE-#272] reservation 상태 변경 영속성 보장 개선

---

backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java

[hotfix] 테스트를 위한 스케줄러 시간 수정

---

frontend/src/pages/Mainpage/components/Signup.jsx
frontend/src/pages/Mainpage/components/TermsandPrivacy.jsx

- 회원가입시 약관 동의를 해야 가입할 수 있도록 기능을 추가했다.
- #268 
본문 내용 검토 필요

[FE-#268] 약관 동의 기능 추가

---

frontend/src/App.jsx
frontend/src/pages/Mainpage/components/Signin.jsx
frontend/src/pages/Mainpage/components/Signup.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- url명이 RESTful하도록 변경하였다.
- #278

[FE-#278] url명 변경

---

backend/src/main/java/com/ice/studyroom/config/WebConfig.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java

- 패널티 인터셉터 제작
- 하단에 기재된 api 이외에는 패널티 여부에 따라 컨트롤러 호출을 방지해두었습니다.
- 최근 예약 조회 : `/api/reservations/my/latest`
- 내 예약 정보 조회 : `/api/reservations/my`
- 스터디룸 일정 조회 : `/api/schedules`
- member 관련 모든 기능 : `/api/users/**`
#275 

[BE-#275] 패널티 인터셉터 제작

---

frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx

- 스터디룸을 선택하게 되면 바로 시간 선택으로 넘어가게 했다.
- #285 

[FE-#285] 스터디룸 선택시 시간 선택으로 변경 로직

---

frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- 로그아웃시 비로그인 메인 화면으로 이동
- #287

[FE-#287] 로그아웃시 비로그인 메인페이지로 이동

---

backend/src/main/java/com/ice/studyroom/config/WebConfig.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/presentation/dto/request/MemberCreateRequest.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java

- 패널티 스케줄러 시간 조정
- 회원가입 비밀번호 규칙 주석제거
- 비밀번호 변경, 기존 비밀번호와 동일할 시 예외 처리
- 인터셉터 경로 변경
- QR 재입장 예외처리
#284 

[BE-#284] 테스트 시나리오 점검

---

frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
frontend/src/pages/ReservationStatus/AttendanceHandler.jsx
frontend/src/pages/ReservationStatus/AttendanceSystem.jsx

- QR코드로 출석할 때 성공과 실패에 따라서 사용자에게 반환되는 메시지를 서버의 응답과 연결하여 변경하였음
- #290 

[FE-#290]예약 실패와 성공시 반환되는 메시지 로직 변경

---

frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
frontend/src/pages/Reservation/handlers/roomBookingManager.jsx

[FE-#292] 토큰 재발급 테스트

---

frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/ReservationStatus/ReservationStatus.jsx

- 전체 예약 조회시 헤더 추가
- 비로그인 접근시 토스트 메세지 생성
- #296

[FE-#296] 전체 예약 조회 헤더 추가

---

frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
frontend/src/pages/ReservationStatus/AttendanceHandler.jsx
frontend/src/pages/ReservationStatus/AttendanceSystem.jsx

- 사용자의 사용감이 불편했던 부분을 수정하였습니다
- #298 

[Fix] 예약 페이지 이동 기능 롤백 & 스터디룸 여백 변경

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/type/ReservationStatus.java
backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ReservationUpdateScheduler.java

- 미 입장 유저의 연장 요청 예외처리
- 단체 예약 시, 1명이라도 입장하지 않았을 경우 연장 요청 예외처리
- 예약 ENTERANCE -> COMPLETED 스케줄러 동작
#301 

[BE-#301] 예약 상태 업데이트 스케줄러 및 연장 예외처리

---

frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx

- 어떤 변경사항이 있는지 설명해주세요.
- #305 

[FE-#305] 개인예약시 참여자 추가 버튼 제거 및 안내 UI 추가

---

frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

- 내 예약 페이지에 COMPLETED 상태를 정상 출석으로 볼 수 있도록 수정함
- #310

[FE-#310] 내 예약 페이지 COMPLETED 상태 추가

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

- 연장 페이지에 개인 예약 조회시 예약자명을 받아오도록 수정함.
- #312

[FE-#312] 연장 페이지 개인 예약 데이터 추가

---

frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

- QR스캐너 페이지의 접근 방식을 변경하면서 기존 버튼을 제거하였다.
- #315 

[Fix] QR 스캐너 페이지 접근 방식 변경

---

frontend/src/pages/Reservation/components/StudyRoomBookingUI.jsx

- 개인 예약용 방에서는 참여자가 추가가 안된다는 메시지 변경
- #305 

[FE-#305] 개인 예약용 방에서는 참여자 추가가 안된다는 메시지 변경

---

frontend/src/pages/Notification/NotificationMessage.jsx

- 패널티 적용된 회원 접근시 Toast Message 구현
#317 

[FE-#317] 패널티 적용된 회원 접근시 Toast Message 구현

---

frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
frontend/src/pages/ReservationStatus/ReservationStatus.jsx

[FE-#311] 페이지 이동 시 페널티 여부 검사

---

backend/src/main/java/com/ice/studyroom/config/WebConfig.java

[hotfix] 인터셉터 예외 URL 오류 처리

---

backend/src/main/java/com/ice/studyroom/config/CorsConfig.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/AESUtil.java

[hotfix] cors 프론트도메인 설정

---

backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java
backend/src/main/java/com/ice/studyroom/global/type/StatusCode.java

- 기존 403 응답 값은 cloud front 에서 변형된 응답을 넘겨주는 것을 확인했습니다. 
이를 우회하고자 새로운 응답값을 정의했습니다.
#322 

[Fix-#322] cloud-front 응답 변경 우회를 위한 새로운 응답 정의

---

frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- 로그아웃 api 요청이 정상적으로 이루어졌는지 확인 후 로그아웃이 되도록, 그렇지 않으면 로그아웃이 되지 않도록 수정했다.
- #326

[FE-#326] 로그아웃 api 호출 확인 후 정상 로그아웃

---

frontend/src/App.jsx
frontend/src/pages/Mainpage/components/AdminSignin.jsx
frontend/src/pages/Mainpage/components/Signin.jsx

- 기존 로그인 페이지에서 ctrl+shift+k를 누르면 관리자 로그인 페이지로 이동 되도록 기능을 추가했다.
- #328

[FE-#328] Admin 로그인 페이지 생성

---

frontend/src/pages/ReservationStatus/AttendanceHandler.jsx

- AT 갱신하는 코드를 새롭게 넣고 적용하였다.
- #330 

[FE-#330] 출석페이지 AT, RT 갱신 관련 수정

---

backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/SecurityConfig.java
backend/src/main/java/com/ice/studyroom/global/exception/GlobalExceptionHandler.java

- api 별로 인증 및 권한을 분류했습니다. 
- 회원가입, 로그인, 이메일 인증 및 코드 검증은 유저의 권한없이도 호출 가능, 그 외에는 유저의 권한이 있어야 호출 가능
- ADMIN 및 ATTENDANT 권한 구분
- #335 

[BE-#335] api 엔드포인트 인증 및 권환 분류

---

frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
frontend/src/pages/Mainpage/handlers/TokenHandler.jsx

- 로그아웃과 비밀번호 변경 진행 시 토큰이 만료됐다면 재발급 후 다시 요청하도록 수정함.
- #334

[FE-#334] 비밀번호 변경, 로그아웃 토큰 만료시 재발급

---

frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

- attendant로 로그인시 출석 페이지로 이동
- #343

[FE-#343] Attendant 로그인 설정

---

frontend/src/pages/Mainpage/components/AdminSignin.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

[FE-#343] Admin 로그인 훅 분리

---

backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/TokenService.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtAuthenticationFilter.java
backend/src/main/java/com/ice/studyroom/domain/identity/infrastructure/security/JwtTokenProvider.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java

- token을 refresh 과정에서 기존 권한이 반영되지 않는 오류를 수정했습니다.
- #346 

[BE-#346] token refresh 시, 기존 권한이 반영되지 않는 오류 수정

---

frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/ReservationStatus/ReservationStatus.jsx

- 전체 예약현황 페이지, 연장 및 취소 기능 토큰 재발급 기능 추가
- #340

[FE-#340] 전체 예약현황 페이지, 연장 및 취소 기능 토큰 재발급 기능 추가

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

- 입실 했을시에만 연장 버튼 클릭 가능하도록 수정
- #349

[FE-#349] 입실하지 않았는데 연장 버튼이 클릭되는 오류 수정

---

frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx

[FE-#354] 토큰 재발급 호출 경로 수정

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

- 연장이 잘 작동하지 않던 것을 수정하고, 토큰 재발급도 잘 이루어지도록 수정
- #356

[FE-#356] 연장 기능 오류 해결 및 토큰 재발급 수정

---

frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
frontend/src/pages/Mainpage/handlers/TokenHandler.jsx
frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
frontend/src/pages/ReservationStatus/ReservationStatus.jsx

- AT가 없을 때 불필요하게 api를 요청하지 않도록 수정했다.
- #359

[FE-#359] AT 없을 때 api 호출하지 않도록 수정

---

.github/workflows/deploy-server.yml
backend/Dockerfile

- jar파일만 활용한 이미지 생성
- gradle 캐싱을 통한 서버 배포 시간 단축
- #361 

[Refactor] 서버 자동 배포 코드 개선

---

backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/global/dto/request/EmailRequest.java
backend/src/main/java/com/ice/studyroom/global/service/GmailService.java
frontend/src/pages/Mainpage/components/Popups.jsx

- front 패널티 관련 내용을 수정하였습니다.
- 예약 완료 안내 메일을 발송하도록 기능을 구현하였습니다.
- #363 

[BE-#363] 예약 완료 안내 이메일 발송 기능

---

backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
backend/src/main/resources/application.properties

- INSERT 쿼리문에 created_at, updated_at 명시
- #365 

[BE-365] 예약 스케줄 INSERT 쿼리문 수정

---

backend/src/main/java/com/ice/studyroom/config/AsyncConfig.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/global/service/EmailService.java
backend/src/main/java/com/ice/studyroom/global/service/GmailService.java

- 예약 완료 이메일 양식을 수정하였습니다.
- 이메일 발송 서비스를 비동기 처리하였습니다.
#367 

[BE-#367] 이메일 발송 기능 비동기 처리

---

frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx

- UTC를 기준으로 날짜를 파싱하여 타임존 차이로 생긴 날짜 계산 오류를 수정
- #374

[FE-#374] 페널티 종료 일자 오류 수정

---

frontend/src/pages/Mainpage/components/QRCodeFetcher.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

- 페널티를 받은 상태라면 QR코드 볼 수 없도록 수정
- #350

[FE-#350] 

---

frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 스터디룸 조회 관련 하드코딩된 부분을 부분적으로 제거하고 schedule을 불러와 보여주도록 변경했다.
- 요일별로 선택할 수 있도록 변경했다.
- #378

[FE-#378] 관리자 페이지 하드코딩 제거

---

backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/type/PenaltyReasonType.java
backend/src/main/resources/application.properties
frontend/src/pages/Mainpage/components/Popups.jsx

- 패널티를 영업일에만 카운팅하도록 변경했습니다.
- 패널티 안내 문구를 변경했습니다.
- jpa 환경 설정을 운영 모드로 변경하였습니다.
#371 

[BE-#371] Penalty 부여일자를 영업일 기준으로 변경

---

frontend/src/pages/Notification/NotificationMessage.jsx

- 기존 스타일에서 성공과 그외의 case의 스타일을 일치시켜 성공과 에러에 따라서 스타일을 변경함
- #369 

[FE-#369] Toast Message의 스타일을 Status에 따라 변경되게 수정

---

frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- Admin 페이지의 선점하기 기능을 구현했다.
- #378

[FE-#378] Admin 선점하기 기능 구현

---

frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx

- admin이 선점한 방을 조회하는 기능을 구현했다.
- #384

[FE-#384] admin 선점된 방 조회 기능 구현

---

frontend/src/App.jsx
frontend/src/pages/Mainpage/components/ProfileDropdown.jsx
frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Mainpage/handlers/PenaltyHandlers.jsx
frontend/src/pages/Mainpage/handlers/UserContext.jsx

- 중복 쿼리를 방지하기 위해 Context Api를 활용하여 전역변수를 활용
- #387

[FE-#387] 중복 쿼리문 방지를 위한 Context Api 사용

---

backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/controller/AdminController.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/request/AdminSetPenaltyRequest.java
backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/AdminPenaltyRecordResponse.java
backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java

- 만료된 패널티 포함 전체 패널티 목록 반환하도록 변경
- 학번을 통해 패널티가 부여되도록 변경
- 패널티 부여일자 필드값 추가
#389 

[BE-#389] admin penalty dto 필드값 수정

---

backend/src/main/java/com/ice/studyroom/domain/admin/infrastructure/persistence/RoomTimeSlotRepository.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/infrastructure/persistence/MemberRepository.java
backend/src/main/java/com/ice/studyroom/domain/penalty/infrastructure/persistence/PenaltyRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ReservationRepository.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/persistence/ScheduleRepository.java

- JPA 레포지토리의 사용하지 않은 함수나 가독성이 떨어지는 함수를 jpql로 개선하였습니다.
- 참고: https://www.notion.so/Spring-data-jpa-1bb7d6c84c71807cb2a8c193a061e8be
#383 

[BE-#383] JPA Repository Refactoring

---

frontend/src/pages/Mainpage/Adminpage/PenaltyLogic.jsx
frontend/src/pages/Mainpage/Adminpage/PenaltyManagement.jsx

- 어드민의 패널티,조회,추가 그리고 해지 기능을 구현
- #392 
- 

[FE-#392] 어드민의 패널티 조회,추가 그리고 해지 기능구현

---

frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 변경된 api에 맞게 코드를 수정했다.
- #378

[FE-#378] admin 선점 변경된 api에 적용

---

frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx

[FE-#398] admin 선점 해지 기능 구현

---

frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 이미 선점된 방 시간대는 선택 안되도록 변경했다.
- #400

[FE-#400] admin 선점하기 페이지 선점 가능한 방 구분

---

backend/src/main/java/com/ice/studyroom/domain/admin/presentation/dto/response/RoomScheduleInfoDto.java
frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/PenaltyLogic.jsx

- 관리자 선점 기능 오류를 해결했습니다.
- UI 문구를 조금 수정했습니다.
#405 
dto 설정을 변경하여 간단하게 해결할 수 있었습니다.

[BE-#405] 관리자 선점 기능 오류 해결

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

- 연장 및 취소 페이지 예약자, 참여자 정보 표시 오류를 수정했다.
- #409

[FE-#409] 예약자 및 참여자 오류 수정

---

frontend/src/pages/Mainpage/Adminpage/Adminpage.jsx
frontend/src/pages/Mainpage/Adminpage/BookingManagement.jsx
frontend/src/pages/Mainpage/Adminpage/PenaltyLogic.jsx
frontend/src/pages/Mainpage/Adminpage/useAdminPageHandler.jsx

- 토큰 재발급 활성화
- 홈, 로그아웃 버튼 활성화
- #414

[FE-#414] Admin 페이지 추가 기능 설정

---

frontend/src/pages/Reservation/handlers/roomBookingManager.jsx

[FE-#420] 예약 요청 데이터 수정

---

backend/src/main/java/com/ice/studyroom/config/RedisConfig.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationCancelTest.java
backend/src/test/java/com/ice/studyroom/domain/reservation/application/ReservationExtendTest.java

- 예약 연장 로직에서 발생할 수 있는 모든 예외에 대한 테스트 코드를 작성했습니다.
- 테스트 항목은 하단 이슈를 참고해주시면 감사하겠습니다.
#418 
테스트 항목 별로 테스트한 내용을 저희 페이지에 따로 남기면 좋을 것 같습니다.

[BE-#418] 예약 연장 테스트 코드 작성

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

[FE-#429] 예약 조회시 데이터 저장 형식 수정

---

frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx
frontend/src/pages/Mainpage/handlers/UserContext.jsx

- Context를 추가하여 로그인시 바로 유저 정보 조회가 가능하도록 변경
- #437

[FE-#437] 메인페이지 유저 정보 업데이트

---

frontend/src/pages/Reservation/StudyRoomManage.jsx

- 연장 시간이 아닐 때 연장 버튼 클릭시 토스트 메세지 생성
- #438

[FE-#438] 연장 시간이 아닐 때 연장 버튼 클릭시 토스트 메세지 생성

---

frontend/src/pages/Mainpage/Mainpage.jsx

- 최근 예약 정보에 스터디룸 이용 시간을 추가했다.
- #457

[FE-#457] 시작, 종료 시간 데이터 추가

---

frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

- QR미리보기 이미지 생성
- 문구 수정
- 팝업 수정
- #459

[FE-#459] QR코드 수정

---

frontend/src/pages/Mainpage/handlers/MemberHandlers.jsx

[FE-#462] 다른 페이지에서 로그인 시도 시 에러 문구 생성

---

frontend/src/pages/Reservation/StudyRoomManage.jsx
frontend/src/pages/Reservation/handlers/roomBookingManager.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx
frontend/src/pages/ReservationStatus/ReservationStatus.jsx

- 비로그인 상태에서 페이지 강제 접근시 메인페이지로 이동
- 토스트 메세지 생성
- #464

[FE-#464] 비로그인 상태에서 페이지 강제 접근시 메인페이지로 이동

---

backend/Dockerfile
backend/build.gradle
backend/src/main/java/com/ice/studyroom/domain/admin/application/AdminService.java
backend/src/main/java/com/ice/studyroom/domain/identity/domain/application/EmailVerificationService.java
backend/src/main/java/com/ice/studyroom/domain/identity/domain/service/CustomUserDetailsService.java
backend/src/main/java/com/ice/studyroom/domain/membership/application/MembershipService.java
backend/src/main/java/com/ice/studyroom/domain/membership/domain/service/MemberDomainService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/application/PenaltyService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/domain/service/PenaltyDomainService.java
backend/src/main/java/com/ice/studyroom/domain/penalty/interceptor/PenaltyCheckInterceptor.java
backend/src/main/java/com/ice/studyroom/domain/penalty/scheduler/PenaltyUpdateScheduler.java
backend/src/main/java/com/ice/studyroom/domain/reservation/application/ReservationService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/domain/entity/Reservation.java
backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/redis/QRCodeService.java
backend/src/main/java/com/ice/studyroom/domain/reservation/scheduler/ScheduleTask.java
backend/src/main/java/com/ice/studyroom/global/filter/LoggingMdcFilter.java
backend/src/main/java/com/ice/studyroom/global/security/service/TokenService.java
backend/src/main/java/com/ice/studyroom/global/service/GmailService.java
backend/src/main/resources/application.properties
backend/src/main/resources/logback-spring.xml

- 핵심 비즈니스 로직에 의미 있는 로그 메시지 추가
- 요청 별로 로그를 분류하기 위해 requestId 생성 및 userEmail 추출 후 MDC에 저장하는 필터 생성
- MDC란, Mapped Diagnostic Context의 약어로 로그에 추가적인 컨텍스트 정보를 제공하는 기능입니다. 
- 각 스레드마다 별도의 컨텍스트 정보를 유지하고 로그 메세지에 추가적인 정보를 포함시키는데 사용됩니다.
- 로그백 설정
- 유효하지 않은 예약에도 QR를 재생성 방지 로직 추가
- #474 
기존에 작성해두었던 문제는 해결시켜두었습니다. 
console에는 그대로 텍스트가 출력되고, 로그 파일에만 JSON이 저장될 예정입니다.

[Feature-#474] 핵심 비즈니스 로직에 의미 있는 로그 메시지 추가

---

.github/workflows/deploy-server.yml

- 컨테이너 내부 /app/logs 경로를 → EC2 호스트 디스크의 /home/ubuntu/backend/logs와 연결하여, 로그 파일이 컨테이너가 삭제돼도 보존되도록 설정했습니다.
- #476 
- 필요한 경우 스크린샷을 첨부해주세요.

[BE-#476] 로그 파일 영속성 설정

---

backend/build.gradle
backend/src/main/java/com/ice/studyroom/config/SecurityConfig.java
backend/src/main/resources/application.properties

- Spring Boot에 Actuator 및 Micrometer를 설정하고 /actuator/prometheus 엔드포인트를 통해 Prometheus가 메트릭을 수집할 수 있도록 구성
#480 
- 필요한 경우 스크린샷을 첨부해주세요.

[BE-#480] Actuator + Micrometer + Prometheus 연동

---

backend/src/main/resources/application.properties

- application.properties에 공통 태그 및 JVM/Tomcat 메트릭 설정 추가
- /actuator/prometheus 엔드포인트가 정상 노출되는지 테스트
- #482 
- 공통 태그 설정을 통해 그라파나 공유 대시보드를 활용할 예정입니다.

[BE-#482] Prometheus 연동을 위한 메트릭 태그 및 JVM 모니터링 속성 추가

---

frontend/src/pages/Mainpage/Mainpage.jsx
frontend/src/pages/Mainpage/components/Signup.jsx

- 회원가입 이용약관 사용성 향상
- +총 예약이 0건인 경우 대비 예약시간 초기값 설정
- #488

[FE-#488] 회원가입 페이지 Usability 향상

---

frontend/src/pages/ReservationStatus/ReservationStatus.jsx

[FE-#489] 예약 현황 페이지 같은 예약 병합처리

---

frontend/src/pages/ReservationStatus/ReservationStatus.jsx

[FE-#498] 취소된 예약이 보여지는 오류 해결

---

backend/src/main/java/com/ice/studyroom/domain/reservation/infrastructure/kafka/VacancyNotificationProducer.java
backend/src/main/java/com/ice/studyroom/domain/reservation/util/ReservationLogUtil.java
backend/src/main/java/com/ice/studyroom/domain/schedule/domain/service/ScheduleCanceller.java
backend/src/main/resources/application.properties

- 메세지 중복 전달을 방지하기 위해서 멱등성 프로듀서를 설정해주었으면 예외 처리 코드를 추가해주었습니다.
- #516 
```properties
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.delivery.timeout.ms=60000
```
- 1분간 재시도를 하도록 변경
- 브로커에 메세지가 중복 전달되지않게 함
```java
@Service
@RequiredArgsConstructor
public class VacancyNotificationProducer {
// 코드 생략
@Async("vacancyNotificationExecutor")
public void sendVacancyNotificationToSubscribers(Long scheduleId, String roomName) {
String redisKey = REDIS_KEY_PREFIX + scheduleId;
Set<Object> subscriberObjects = redisTemplate.opsForHash().keys(redisKey);
if (subscriberObjects.isEmpty()) {
ReservationLogUtil.log("빈자리 알림을 신청한 구독자가 존재하지 않습니다. 스케줄 ID: " + scheduleId);
return;
}
Set<String> subscribers = subscriberObjects.stream()
.map(String::valueOf) …
```

[BE-#516] 빈자리 알림 카프카 멱등성 프로듀서 설정 및 예외 처리 추가

---

frontend/src/pages/Mainpage/handlers/MainpageHandlers.jsx
frontend/src/pages/Notification/NotificationMessage.jsx
frontend/src/pages/ReservationStatus/MyReservationStatus.jsx

- 만료된 QR 조회시 응답에 맞게 toast message를 띄우도록 수정함.
- #532

[FE-#532] QR 조회 toast message 추가
